### ISSUE TITLE
NotSpecified: (:) [Write-Error], WriteErrorException - AFter login

### ISSUE THREAD

**Issue by d4-maertzdorf** [MG-Cloudflow/Intune-Toolkit#2]
@.\Main.ps1
Failed to load configuration policies. Error: Index operation failed; the array index evaluated to null.
At line:1 char:1
+ .\Main.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

Failed to load device configurations. Error: Index operation failed; the array index evaluated to null.
At line:1 char:1
+ .\Main.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

1) connect to graph
2) accept permissions for organisation
3) press any of the buttons on the left side e.g. configuration policies, device configuration, compliance, templates or the applications.

Ran the application after pulling it using git

stored in c:\users\username\Intune-Toolkit

**Comment by MG-Cloudflow** [comment]
Hey 

could you send me the log file it should be in the root. folder

**Comment by d4-maertzdorf** [comment]
[IntuneToolkit.log](https://github.com/user-attachments/files/15972705/IntuneToolkit.log)

**Comment by d4-maertzdorf** [comment]
<![LOG[Failed to load applications. Error: Index operation failed; the array index evaluated to null.]LOG]!><time=\15:58:48.820+02:00\ date=\06-25-2024\ component=\Applications-Button\ context=\\ type=\1\ thread=\17\ file=\ApplicationsButton.ps1\>

**Comment by MG-Cloudflow** [comment]
I'll close this because of local powershell issue and also implemented extra permissions for the applications.

[Fix Permission DeviceManagementApps.ReadWrite.All](https://github.com/MG-Cloudflow/Intune-Toolkit/commit/90851fed10b55e3f59846a52cee40fe72dd9fe8f)
