### ISSUE TITLE
v0.2.5-alpha: Failed to load and display the window: You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by schmittnieto** [MG-Cloudflow/Intune-Toolkit#24]
Hello everyone,

I am trying to use the new v0.2.5-alpha and encounter the following error when running the script:

``` powershell
.\Main.ps1
Show-Window: C:\Temp\Intune-Toolkit\Main.ps1:190
Line |
 190 |  Show-Window
     |  ~~~~~~~~~~~
     | Failed to load and display the window: You cannot call a method on a null-valued expression.
```

**My PowerShell version is as follows:**
```
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
If you require more information, please feel free to contact me directly.

Best regards,
Cristian

**Comment by MG-Cloudflow** [comment]
Hey Cristian

Did you download from main or from the release.
Because i had a little oopsie in main while merging to my dev branch ;-)
But Main branch is fixed again so if you download that version that could be the issue

if not could you send me the log file

**Comment by schmittnieto** [comment]
Hello Maxime, 

as you said it is now working properly, thanks for the prompt reply!

Best regards,
Cristian
