### ISSUE TITLE
Can't assign Windows Applications

### ISSUE THREAD

**Issue by leonatwork** [MG-Cloudflow/Intune-Toolkit#25]
Hey, 
Windows Applications can't be assigned as the following Error Message is prompted: 
---------------------------
Error
---------------------------
Failed to add assignments. Error: Response status code does not indicate success: BadRequest (Bad Request).
---------------------------
OK   
---------------------------
Assigning Policies working like a charm!

**Comment by MG-Cloudflow** [comment]
Hey

Could you share me your log file ?
C:\Users\USERNAMEAppData\Local\Temp\IntuneToolkit.log

kind regards
maxime

**Comment by MG-Cloudflow** [comment]
Hey

is the application a Microsoft Store app (new) ?

because  i found an issue with that kind of application trying to fix it now.
