### ISSUE TITLE
"Microsoft.Graph module is installed" check and module dependency idea

### ISSUE THREAD

**Issue by MrMontesa** [MG-Cloudflow/Intune-Toolkit#28]
Hey,
great app idea you had. I wanted to give your app a try and it fails on checking for the graph modules.
We dont install the bloated 39 modules from meta package `Microsoft.Graph`, but only selected ones, that are required for a certain job.
Thats why 
```
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph)) {
```
fails.
making it
```
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
```
does work.
Perhaps an idea...

And anohter one:
You might want to check for detailed module requirements at the very beginning. When running the tool it seemed to freeze, but in the end was installing some dependencies of required modules (e.g. Microsoft.Graph.Compliance).
Suggestion would be to either use `#Requires ModuleX` at the beginning and have powershell hard fail with standard error message.
Or alternatively, do some if-tesing for module presence and install inline, if needed.
Thanks a lot.
best

**Comment by MG-Cloudflow** [comment]
Hey,

Thank you for the feedback and indeed a good idea i was actualy already working on this.
But needed to do some further testing. i'll keep the issue open until its implemented.

kind regards
maxime

**Comment by MG-Cloudflow** [comment]
IHey

n the new release, I streamlined the installation of Graph modules to include only the necessary sub-modules. Now, the only required module is Microsoft.Graph.Authentication.
