### ISSUE TITLE
Graph Permissions in customer Tenants

### ISSUE THREAD

**Issue by leonatwork** [MG-Cloudflow/Intune-Toolkit#29]
Hey, 
We currently facing the problem, that we can't use the tool in one of our customers envoirnments as the Graph API Permissions are not sufficent. 
It's currently not possible to grant these permissions through the tool. 
Is there a best practices regarding deploying a enterprise application in combination with the Intune Toolkit? 

Thank you!

**Comment by MG-Cloudflow** [comment]
Hey Leon

Just create an app registration and give the app the following permission i indeed dit not document it yet. ill add it to my list of to do.

![image](https://github.com/user-attachments/assets/539fda21-eb2c-4177-b648-fb8ffad641ab)

**Comment by MG-Cloudflow** [comment]
No problem
